version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-portfolio
    ports:
      - "80:80"
    restart: always
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge