name: Deploy to Server

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Copy Docker files to server
        run: |
          scp -o StrictHostKeyChecking=no -P 11827 Dockerfile docker-compose.yml ubuntu@0.tcp.ngrok.io:~/portfolio/
          scp -o StrictHostKeyChecking=no -P 11827 -r ./* ubuntu@0.tcp.ngrok.io:~/portfolio/

      - name: Deploy with Docker
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@0.tcp.ngrok.io -p 11827 "cd ~/portfolio && docker-compose down && docker-compose up -d --build"
