name: SSH Connection Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no ubuntu@0.tcp.ngrok.io -p 11827 "echo Connection successful"
